name: NPM packages publish

on:
  push:
    branches:
      - release

jobs:
  npm-publish:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          scope: '@picturepark'

      - name: Build
        run: |
          npm install
          npm run build:fetch
          npm run build:pickers

      - name: Build Angular V2 libraries
        working-directory: ./src/picturepark-sdk-v2-angular
        run: |
          npm run init
          npm run lint
          npm run build-libraries

      - name: Publish npm packages
        working-directory: ./src/
        run: |
          npm publish 'picturepark-sdk-v1-fetch' --access=public
          npm publish 'picturepark-sdk-v1-pickers' --access=public
          npm publish 'picturepark-sdk-v2-angular/dist/picturepark-sdk-v2-angular' --access=public
          npm publish 'picturepark-sdk-v2-angular/dist/picturepark-sdk-v2-angular-oidc' --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  
